---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
  namespace: biz
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: candy
      containers:
      - image: registry.cn-hongkong.aliyuncs.com/imtoken/candy:lala
        name: candy
