---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo1
  namespace: biz
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: candy
      containers:
      - image: registry.cn-hongkong.aliyuncs.com/imtoken/candy:k1
        name: candy
