---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    fluxcd.io/tag.candy: glob:master-*
  name: podinfo1
  namespace: biz
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: candy
      containers:
      - image: registry.cn-hongkong.aliyuncs.com/imtoken/candy:k2
        name: candy
