---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo2
  namespace: exchange
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: candy
      containers:
      - image: registry.cn-hongkong.aliyuncs.com/imtoken/candy:k4
        name: candy
