---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: candy1
  namespace: biz
  labels:
    app: candy1
  annotations:
    fluxcd.io/automated: "true"
spec:
  selector:
    matchLabels:
      app: candy1
  template:
    metadata:
      labels:
        app: candy1
    spec:
      containers:
      - name: candy1
        image: registry.cn-hongkong.aliyuncs.com/imtoken/candy:master
        imagePullPolicy: Always
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
        ports:
        - containerPort: 80
          protocol: TCP
      nodeSelector:
        biz: "true"
      imagePullSecrets:
      - name: image-registry-secret
